apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
spec:
  ports:
  - port: 9080
    name: http
  selector: {}
---
# inside of the mesh, redirect "details" to details.svc.a.remote
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
spec:
  gateways:
  - mesh
  hosts:
  - details.default.svc.cluster.local
  http:
  - rewrite:
      authority: details.svc.b.remote
    route:
    - destination:
        host: ingress.b.remote
        port:
          number: 80
      weight: 100
