apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector: {}
---
# inside of the mesh, redirect "reviews" to reviews.svc.a.remote
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  gateways:
  - mesh
  hosts:
  - reviews.default.svc.cluster.local
  http:
  - rewrite:
      # do the header re-write so we can ingress via host
      authority: reviews.svc.b.remote
    route:
    - destination:
        host: ingress.b.remote
        port:
          number: 80
      weight: 100
